# Solving Sudoku problem using Simulated Annealing

## Sudoku instances

More Sudoku instnaces can be found here: https://sudoku.com/evil/

In [1]:
# Trivial Sudoku
Sudoku_triv = [
    [7, 0, 0, 0, 6, 0, 9, 0, 5],
    [5, 0, 0, 0, 2, 7, 0, 0, 0],
    [0, 0, 0, 0, 3, 5, 7, 8, 4],
    [9, 8, 6, 5, 0, 0, 0, 0, 0],
    [2, 1, 0, 3, 0, 8, 5, 0, 6],
    [0, 5, 0, 6, 0, 2, 1, 9, 8],
    [8, 7, 3, 4, 1, 0, 2, 0, 9],
    [0, 2, 5, 0, 0, 0, 0, 3, 1],
    [4, 0, 0, 0, 0, 0, 8, 6, 0],
]


# Easy Sudoku
Sudoku_easy = [
    [9, 0, 7, 3, 0, 8, 0, 0, 0],
    [4, 2, 0, 0, 0, 0, 3, 0, 1],
    [1, 0, 8, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 6, 3, 0, 4, 0, 7],
    [6, 5, 0, 1, 0, 7, 0, 3, 2],
    [3, 0, 1, 0, 9, 4, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 9],
    [7, 0, 6, 0, 0, 0, 0, 4, 3],
    [0, 0, 0, 7, 0, 1, 2, 0, 5],
]

# Medium Sudoku
Sudoku_med = [
    [7, 0, 0, 0, 0, 6, 0, 0, 0],
    [0, 2, 0, 4, 0, 1, 0, 3, 7],
    [0, 1, 0, 0, 0, 0, 0, 0, 5],
    [3, 0, 1, 0, 0, 2, 0, 8, 9],
    [0, 7, 0, 0, 0, 0, 0, 1, 0],
    [4, 9, 0, 7, 0, 0, 5, 0, 6],
    [9, 0, 0, 0, 0, 0, 0, 5, 0],
    [5, 3, 0, 8, 0, 4, 0, 7, 0],
    [0, 0, 0, 5, 0, 0, 0, 0, 3],
]

# Hard Sudoku
Sudoku_hard = [
    [9, 0, 0, 1, 0, 0, 0, 5, 4],
    [0, 0, 0, 0, 8, 0, 0, 0, 0],
    [0, 0, 5, 0, 0, 9, 0, 0, 3],
    [0, 9, 0, 0, 3, 5, 0, 4, 1],
    [0, 0, 0, 0, 1, 0, 0, 0, 0],
    [4, 1, 0, 2, 6, 0, 0, 8, 0],
    [7, 0, 0, 3, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 4, 0, 0, 0, 0],
    [3, 5, 0, 0, 0, 1, 0, 0, 6],
]

# Evil Sudoku
Sudoku_evil = [
    [5, 9, 0, 0, 6, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 4, 0, 0, 0],
    [0, 2, 1, 9, 0, 0, 0, 0, 0],
    [0, 0, 9, 0, 0, 0, 8, 0, 5],
    [0, 0, 4, 1, 5, 8, 3, 0, 0],
    [8, 0, 3, 0, 0, 0, 7, 0, 0],
    [0, 0, 0, 0, 0, 2, 6, 4, 0],
    [0, 0, 0, 3, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 7, 0, 0, 5, 8],
]

## Select a Sudoku problem to be solved

In [2]:
sudokuTobeSolved=Sudoku_med

In [3]:
from optalgotools.problems import Sudoku

# Create an instance of Sudoku problem
sudoku_prob = Sudoku(sudokuTobeSolved)

# visualize the selected Sudoku instance
sudoku_prob.print()

▄■■■■■┬■■■■■┬■■■■■▄■■■■■┬■■■■■┬■■■■■▄■■■■■┬■■■■■┬■■■■■▄
█  7  |     |     █     |     |  6  █     |     |     █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█     |  2  |     █  4  |     |  1  █     |  3  |  7  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█     |  1  |     █     |     |     █     |     |  5  █
█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█
█  3  |     |  1  █     |     |  2  █     |  8  |  9  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█     |  7  |     █     |     |     █     |  1  |     █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  4  |  9  |     █  7  |     |     █  5  |     |  6  █
█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█
█  9  |     |     █     |     |     █     |  5  |     █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  5  |  3  |     █  8  |     |  4  █     |  7  |     █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█     |     |     █  5  |     |     █     |     

## Solving Sudoku using PuLP

In [4]:
# The Sudoku Problem Formulation for the PuLP Modeller
# Authors: Antony Phillips, Dr Stuart Mitcehll

import numpy as np
# from time import time
import datetime
from pulp import *

# A list of strings from 1 to 9 is created
Sequence = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# The Vals, Rows and Cols sequences all follow this form
Vals = Sequence
Rows = Sequence
Cols = Sequence

# SquareBoxes list with the row and column index of each square
squareBoxes =[]
for i in range(3):
    for j in range(3):
        squareBoxes += [[(Rows[3*i+k],Cols[3*j+l]) for k in range(3) for l in range(3)]]
        
# Define Problem       
prob = LpProblem("Sudoku Problem",LpMinimize)

# Creating a Set of Variables
choices = LpVariable.dicts("Choice",(Vals,Rows,Cols),0,1,LpInteger)

# Added arbitrary objective function
prob += 0, "Arbitrary Objective Function"

# Setting Constraints
# A constraint ensuring that only one value can be in each square is created
for r in Rows:
    for c in Cols:
        prob += lpSum([choices[v][r][c] for v in Vals]) == 1, ""

# The row, column and box constraints are added for each value
for v in Vals:
    for r in Rows:
        prob += lpSum([choices[v][r][c] for c in Cols]) == 1,""
        
    for c in Cols:
        prob += lpSum([choices[v][r][c] for r in Rows]) == 1,""

    for b in squareBoxes:
        prob += lpSum([choices[v][r][c] for (r,c) in b]) == 1,""
                        
# The starting numbers are entered as constraints             
for r in range(len(sudokuTobeSolved)):
    for c in range(len(sudokuTobeSolved[r])):
        value = sudokuTobeSolved[r][c]
        if value != 0:
            prob += choices[value][r + 1][c + 1] == 1,""

start = datetime.datetime.now()          
# The problem is solved using PuLP's choice of Solver
prob.solve()
end = datetime.datetime.now()

# The status of the solution is printed to the screen
print("Status:", LpStatus[prob.status])
print("Time to find the solution %s seconds" %(end-start))

c:\Users\Alaa\.conda\envs\ox\lib\site-packages\pulp\pulp.py:1352: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


Status: Optimal
Time to find the solution 0:00:00.796072 seconds


In [5]:
# visualize the solution
soln=[]
for r in Rows:
    for c in Cols:
        for v in Vals:
            if choices[v][r][c].varValue == 1:               
                soln.append(v)
                
sudoku_sol=np.array(soln).reshape(9, 9).tolist()
sudoku_sol = Sudoku(sudoku_sol)
sudoku_sol.print()                

▄■■■■■┬■■■■■┬■■■■■▄■■■■■┬■■■■■┬■■■■■▄■■■■■┬■■■■■┬■■■■■▄
█  7  |  4  |  3  █  2  |  5  |  6  █  1  |  9  |  8  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  8  |  2  |  5  █  4  |  9  |  1  █  6  |  3  |  7  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  6  |  1  |  9  █  3  |  7  |  8  █  2  |  4  |  5  █
█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█
█  3  |  5  |  1  █  6  |  4  |  2  █  7  |  8  |  9  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  2  |  7  |  6  █  9  |  8  |  5  █  3  |  1  |  4  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  4  |  9  |  8  █  7  |  1  |  3  █  5  |  2  |  6  █
█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█
█  9  |  6  |  4  █  1  |  3  |  7  █  8  |  5  |  2  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  5  |  3  |  2  █  8  |  6  |  4  █  9  |  7  |  1  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  1  |  8  |  7  █  5  |  2  |  9  █  4  |  6  

# Solving Sudoku using backtracking

In [6]:
sudoku_prob.reset()
start = datetime.datetime.now()     
sudoku_prob.solve_backtrack()
end = datetime.datetime.now()
print("Time to find the solution %s seconds" %(end-start))

Time to find the solution 0:00:00.006998 seconds


In [7]:
sudoku_prob.print()

▄■■■■■┬■■■■■┬■■■■■▄■■■■■┬■■■■■┬■■■■■▄■■■■■┬■■■■■┬■■■■■▄
█  7  |  4  |  3  █  2  |  5  |  6  █  1  |  9  |  8  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  8  |  2  |  5  █  4  |  9  |  1  █  6  |  3  |  7  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  6  |  1  |  9  █  3  |  7  |  8  █  2  |  4  |  5  █
█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█
█  3  |  5  |  1  █  6  |  4  |  2  █  7  |  8  |  9  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  2  |  7  |  6  █  9  |  8  |  5  █  3  |  1  |  4  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  4  |  9  |  8  █  7  |  1  |  3  █  5  |  2  |  6  █
█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█
█  9  |  6  |  4  █  1  |  3  |  7  █  8  |  5  |  2  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  5  |  3  |  2  █  8  |  6  |  4  █  9  |  7  |  1  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  1  |  8  |  7  █  5  |  2  |  9  █  4  |  6  

# Solving Sudoku using our SA implementation in optimization_algorithms_tools

In [8]:
from optalgotools.algorithms import SimulatedAnnealing

sa = SimulatedAnnealing(max_iter=100000, max_iter_per_temp=1000, initial_temp=500, final_temp=0.001, cooling_schedule='geometric', cooling_alpha=0.9, debug=1)

In [9]:
sudoku_prob.reset()
start = datetime.datetime.now()     
sa.run(sudoku_prob, 0)
end = datetime.datetime.now()
print("Time to find the solution %s seconds" %(end-start))

Simulated annealing is initialized:
current value = 26, current temp=500
Optimal solution reatched!: 
curr iter: 1, curr best value: 0, curr temp:500, curr best: sol: [[7 4 3 2 5 6 1 9 8]
 [8 2 5 4 9 1 6 3 7]
 [6 1 9 3 7 8 2 4 5]
 [3 5 1 6 4 2 7 8 9]
 [2 7 6 9 8 5 3 1 4]
 [4 9 8 7 1 3 5 2 6]
 [9 6 4 1 3 7 8 5 2]
 [5 3 2 8 6 4 9 7 1]
 [1 8 7 5 2 9 4 6 3]]
Time to find the solution 0:00:00.562091 seconds


In [10]:
# visualize best solution found

sudoku_sol=np.array(sa.s_best).reshape(9, 9).tolist()
sudoku_sol = Sudoku(sudoku_sol)
sudoku_sol.print()    

▄■■■■■┬■■■■■┬■■■■■▄■■■■■┬■■■■■┬■■■■■▄■■■■■┬■■■■■┬■■■■■▄
█  7  |  4  |  3  █  2  |  5  |  6  █  1  |  9  |  8  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  8  |  2  |  5  █  4  |  9  |  1  █  6  |  3  |  7  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  6  |  1  |  9  █  3  |  7  |  8  █  2  |  4  |  5  █
█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█
█  3  |  5  |  1  █  6  |  4  |  2  █  7  |  8  |  9  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  2  |  7  |  6  █  9  |  8  |  5  █  3  |  1  |  4  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  4  |  9  |  8  █  7  |  1  |  3  █  5  |  2  |  6  █
█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█■■■■■┼■■■■■┼■■■■■█
█  9  |  6  |  4  █  1  |  3  |  7  █  8  |  5  |  2  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  5  |  3  |  2  █  8  |  6  |  4  █  9  |  7  |  1  █
█─────┼─────┼─────█─────┼─────┼─────█─────┼─────┼─────█
█  1  |  8  |  7  █  5  |  2  |  9  █  4  |  6  

In [11]:
# show iterations
sa_hand_iter = SimulatedAnnealing(max_iter=100000, max_iter_per_temp=10, initial_temp=500, final_temp=0.0001, cooling_schedule='linear_inverse', cooling_alpha=0.9, debug=2)

sudoku_prob.reset()
sa_hand_iter.run(sudoku_prob, 0)

Simulated annealing is initialized:
current value = 26, current temp=500
curr iter: 1, curr value: 25, curr best value: 25, curr temp:500, curr best: sol: [[7 5 4 3 3 6 9 2 2]
 [8 2 6 4 5 1 9 3 7]
 [8 1 3 9 9 7 6 4 5]
 [3 6 1 6 5 2 7 8 9]
 [8 7 2 3 3 3 4 1 2]
 [4 9 8 7 8 3 5 2 6]
 [9 8 8 2 2 7 2 5 4]
 [5 3 2 8 1 4 2 7 2]
 [6 4 4 5 9 9 9 9 3]]
curr iter: 2, curr value: 27, curr best value: 25, curr temp:263.15789473684214, curr best: sol: [[7 5 4 3 3 6 9 2 2]
 [8 2 6 4 5 1 9 3 7]
 [8 1 3 9 9 7 6 4 5]
 [3 6 1 6 5 2 7 8 9]
 [8 7 2 3 3 3 4 1 2]
 [4 9 8 7 8 3 5 2 6]
 [9 8 8 2 2 7 2 5 4]
 [5 3 2 8 1 4 2 7 2]
 [6 4 4 5 9 9 9 9 3]]
curr iter: 3, curr value: 24, curr best value: 24, curr temp:178.57142857142858, curr best: sol: [[7 4 5 3 3 6 1 9 2]
 [8 2 6 4 5 1 6 3 7]
 [6 1 3 9 9 7 8 4 5]
 [3 6 1 6 4 2 7 8 9]
 [2 7 5 3 3 9 4 1 2]
 [4 9 8 7 8 8 5 2 6]
 [9 8 8 2 2 7 2 5 4]
 [5 3 2 8 1 4 2 7 2]
 [1 6 4 5 9 9 9 9 3]]
curr iter: 4, curr value: 27, curr best value: 24, curr temp:135.13513513513513, 